name: TISHA_extra
favicon: null
layout_spectrum: 0.06991568743251264
typography_spectrum: 0.386025813408196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9029620403889567
  lightness: 0.36864507012069225
  saturation: 0.7750662476755679
  rhythmicContrast: 0.34183943178504705
purpose: []
